### ISSUE TITLE
Laravel crashes when no incoming webhook exists

### ISSUE THREAD

**Issue by jurienhamaker** [chilion/Slack#4]
When a user got deleted in slack which has the ownership over an webhook, slack automatically deletes the webhook too.

The problem here is that your packages makes laravel stop working all over when slack returns an error.

Maybe try catching it and logging it instead of throwing an exception where the rest of the code would stop working.

**Comment by chilion** [comment]
Hmm. Good point. I'll look into it once I have time. Perhaps someone else has the time, create a PR ;-)

**Comment by chilion** [comment]
Appearantly this happens when you don't failsave your own code. The package only returns true of false.
